version: "3.3"

services:
  db:
    image: postgres:13
    env_file:
      - .env
    container_name: db_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"

  backend:
    build:
      context: .
      dockerfile: ./src/django_project/Dockerfile
    container_name: billing
    hostname: billing
    user: root
    environment:
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: